### ISSUE TITLE
TimeOut when signing an already signed version of an addon

### ISSUE THREAD

**Issue by laedit** [mozilla/sign-addon#241]
I was trying to setup a CI for build & sign a webextension at each push when I encountered a timeout each time I was calling the `web-ext sign` command.

It appears that it happens if you try to sign an already signed version of an addon, in my case the version haven't be incremented in the last commit.

Stacktrace:

```
sign: Error: Validation took too long to complete;
     at Timeout._onTimeout (C:\NPM\Modules\node_modules\web-ext\node_modules\sign-addon\dist\webpack:\src\amo-client.js:222:16)
     at tryOnTimeout (timers.js:224:11)
     at Timer.listOnTimeout (timers.js:198:5)
```

I am fine with not signing an already signed version but it is preferable to have a precise exception than a timeout.

**Comment by kumar303** [comment]
Huh, I haven't seen that. It sounds like you are able to reproduce it each time. Could you provide some more specific steps or perhaps include the source of an add-on that I could look at?

When I try to sign an add-on version that has already been signed, I get an error as expected:

````
$ web-ext sign --api-key ... --api-secret ... --api-url-prefix https://addons-dev.allizom.org/api/v3
Building web extension from /Users/kumar/tmp/addons/web-ext-no-id
Using previously auto-generated extension ID: {891d2b67-1bbb-45b6-8f64-32772815a884}
Server response: Version already exists. (status: 409)
FAIL

sign: WebExtError: The WebExtension could not be signed
    at _callee$ (/Users/kumar/dev/web-ext/dist/webpack:/src/cmd/sign.js:124:15)
    at tryCatch (/Users/kumar/dev/web-ext/node_modules/regenerator-runtime/runtime.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/kumar/dev/web-ext/node_modules/regenerator-runtime/runtime.js:335:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/kumar/dev/web-ext/node_modules/regenerator-runtime/runtime.js:96:21)
    at step (/Users/kumar/dev/web-ext/dist/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:17:1)
    at /Users/kumar/dev/web-ext/dist/webpack:/~/babel-runtime/helpers/asyncToGenerator.js:28:1
    at run (/Users/kumar/dev/web-ext/dist/webpack:/~/core-js/library/modules/es6.promise.js:87:1)
    at /Users/kumar/dev/web-ext/dist/webpack:/~/core-js/library/modules/es6.promise.js:100:1
    at flush (/Users/kumar/dev/web-ext/dist/webpack:/~/core-js/library/modules/_microtask.js:18:1)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
````

**Comment by laedit** [comment]
My bad, I can't reproduce it today: yesterday I can't try it at work on my computer so I only tried on VisualStudioOnline, but right now I can't reproduce it at all, neither on my computer, on VSO or on [AppVeyor](https://ci.appveyor.com/project/laedit/webextappveyorsign).
For the record, yesterday I was able to reproduce it with [this light addon](https://github.com/laedit/WebExtAppVeyorSign).
I guess it was a temporary bug from VSO.

**Comment by kumar303** [comment]
ok, thanks for following up and thanks for your initial bug report. It sounds like you ran into some legitimate performance issues with out signing service, sorry about that. I checked out your source and I was able to sign it just fine (on our dev server).
