### ISSUE TITLE
Attemping to use npm modules gives multpile import failures

### ISSUE THREAD

**Issue by Standard8** [mozilla/sign-addon#28]
I'm attempting to import the module from npm for use as per the README. However, I'm getting various errors which seem to be missing dependencies, that I typically expect the package to provide (especially as some have multiple values), rather than having to provide myself

In my script:
``js
var signAddon = require('sign-addon');
```

My package.json started with just `"sign-addon": "0.0.1",` I then had to find and add modules for the items below - as the dist file in the node_modules directory didn't include them.

```shell
module.js:338
    throw err;
          ^
Error: Cannot find module 'source-map-support'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

```shell
Error: Cannot find module 'any-promise'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:244:19)
    at __webpack_require__ (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:22:30)
    at Object.<anonymous> (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:180:16)
    at __webpack_require__ (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:22:30)
    at Object.<anonymous> (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:57:12)
    at __webpack_require__ (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:22:30)
```

```shell
Error: Cannot find module 'thenify-all'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:262:19)
    at __webpack_require__ (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:22:30)
    at Object.<anonymous> (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:222:2)
    at __webpack_require__ (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:22:30)
    at Object.<anonymous> (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:57:12)
    at __webpack_require__ (/Users/mark/loop/loop/node_modules/sign-addon/dist/sign-addon.js:22:30)
```

**Comment by kumar303** [comment]
It sounds like you are using a buggy version of npm. What version of node and npm are you using?

**Comment by Standard8** [comment]
I was using npm 2.something. Upgrading to npm 3 works.

**Comment by kumar303** [comment]
What version of Node were you using it with? I'd like to document this for others.

**Comment by kumar303** [comment]
Oh, duh, I figured out the real problem. [This banner](https://github.com/mozilla/web-ext/blob/master/webpack.config.js#L55) adds a source-map-support import at the top of the distributed file so it needs to be an explicit dependency. I think it only worked before because of how newer npm versions flatten dependencies (something else was depending on source-map-support).

**Comment by Standard8** [comment]
Aha, great thanks for that!
