### ISSUE TITLE
test.amo-client.js: signing: 'signing lets you sign an add-on' times out occasionally

### ISSUE THREAD

**Issue by kumar303** [mozilla/sign-addon#31]
This test times out sometimes when Travis is overloaded. Perhaps we just need to increase the timeout. Or maybe some I/O heavy parts can be mocked further.

````
  1) amoClient.Client signing lets you sign an add-on:

     Error: timeout of 1000ms exceeded. Ensure the done() callback is being called in this test.
      at tryCatchReject (node_modules/when/lib/makePromise.js:845:30)
      at runContinuation1 (node_modules/when/lib/makePromise.js:804:4)
      at Fulfilled.when (node_modules/when/lib/makePromise.js:592:4)
      at Pending.run (node_modules/when/lib/makePromise.js:483:13)
      at Scheduler._drain (node_modules/when/lib/Scheduler.js:62:19)
      at Scheduler.drain (node_modules/when/lib/Scheduler.js:27:9)
````

**Comment by kumar303** [comment]
I increased the timeout in https://github.com/mozilla/sign-addon/pull/41, hopefully that's all that was needed.
