### ISSUE TITLE
test 'makes requests with an auth token' sometimes fails

### ISSUE THREAD

**Issue by kumar303** [mozilla/sign-addon#42]
The test in `tests/test.amo-client.js` named 'makes requests with an auth token' sometimes fails. I think it is related to the timing of checking a JWT (which naturally involves timestamps).

**Comment by kumar303** [comment]
Example failure:
````
0m  1) amoClient.Client requests makes requests with an auth token:

      AssertionError: expected { Object (url, headers) } to deeply equal { Object (url, headers) }
      + expected - actual
       {
         "headers": {
           "Accept": "application/json"
      -    "Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmYWtlLWFwaS1rZXkiLCJpYXQiOjE0Njc3NDYwMzYsImV4cCI6MTQ2Nzc0NjA5Nn0.YrKkrm08VhhboPo5hENjKF8LeJLOtCjauWNMugCcDA8"
      +    "Authorization": "JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmYWtlLWFwaS1rZXkiLCJpYXQiOjE0Njc3NDYwMzcsImV4cCI6MTQ2Nzc0NjA5N30.nbNXL1Z1K7UX_8heMMIENlytnSDLFaMKTa5aQYXJBIw"
         }
         "url": "http://not-a-real-amo-api.com/api/v3/somewhere"
       }
      
      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at dist/webpack:/tests/test.amo-client.js:559:38
      at tryCatchReject (node_modules/when/lib/makePromise.js:845:30)
      at runContinuation1 (node_modules/when/lib/makePromise.js:804:4)
      at Fulfilled.when (node_modules/when/lib/makePromise.js:592:4)
      at Pending.run (node_modules/when/lib/makePromise.js:483:13)
      at Scheduler._drain (node_modules/when/lib/Scheduler.js:62:19)
      at Scheduler.drain (node_modules/when/lib/Scheduler.js:27:9)
````
