### ISSUE TITLE
Server errors can be confusing

### ISSUE THREAD

**Issue by kumar303** [mozilla/sign-addon#75]
You may receive an error from the API server like:

    {"detail":"Signature has expired."}

this has nothing to with signing an extension so it's confusing. All server errors should be prefixed, maybe like:

    {"detail":"Error communicating with the signing service: Signature has expired."}

**Comment by kumar303** [comment]
I don't think this is actually so confusing. When you run it from something like [web-ext](https://github.com/mozilla/web-ext), it's pretty clear that you're getting a server error. This isn't the exact same error but you get the idea:
````
$ web-ext sign --api-key ... --api-secret ... --api-url-prefix https://addons-dev.allizom.org/api/v3
Building web extension from /Users/kumar/dev/webextensions-examples/beastify
Your web extension is ready: /var/folders/h7/rttdqkks7fl_txp9_rr4j4840000gn/T/tmp-web-ext-47421cWnp19aVLXEl/beastify-1.0.zip
Using previously auto-generated extension ID: {cf3c69a7-f889-447c-9d6b-7694be803513}

sign: Error: Received bad response from the server while requesting https://addons-dev.allizom.org/api/v3/addons/%7Bcf3c69a7-f889-447c-9d6b-7694be803513%7D/versions/1.0/

status: 401
response: {"detail":"Unknown JWT iss (issuer)."}
headers: {"allow":"GET, POST, PUT, HEAD, OPTIONS","content-security-policy":"script-src 'self' https://addons.mozilla.org https://www.paypalobjects.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://addons-dev.allizom.org https://addons-dev-cdn.allizom.org; default-src 'self'; img-src 'self' data: blob: https://www.paypal.com https://ssl.google-analytics.com https://addons.cdn.mozilla.net https://static.addons.mozilla.net https://sentry.prod.mozaws.net https://addons-dev-cdn.allizom.org; media-src https://videos.cdn.mozilla.net; style-src 'self' 'unsafe-inline' https://addons.cdn.mozilla.net https://addons-dev-cdn.allizom.org; frame-src 'self' https://ic.paypal.com https://paypal.com https://www.google.com/recaptcha/ https://www.paypal.com https://www.sandbox.paypal.com; object-src 'none'; connect-src 'self' https://sentry.prod.mozaws.net; font-src 'self' https://addons.cdn.mozilla.net https://addons-dev-cdn.allizom.org; report-uri /__cspreport__","content-type":"application/json","date":"Tue, 05 Jul 2016 21:44:16 GMT","etag":"\"76adbaf90ae97a9c280dac5adb570a33\"","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Tue, 05-Jul-2016 21:44:31 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"X-Mobile, User-Agent","www-authenticate":"JWT realm=\"api\"","x-content-type-options":"nosniff","x-frame-options":"DENY","x-xss-protection":"1; mode=block","transfer-encoding":"chunked","connection":"Close"}

    at /Users/kumar/dev/sign-addon/dist/webpack:/src/amo-client.js:105:15
    at tryCatchReject (/Users/kumar/dev/sign-addon/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/kumar/dev/sign-addon/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/kumar/dev/sign-addon/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/kumar/dev/sign-addon/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/kumar/dev/sign-addon/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/kumar/dev/sign-addon/node_modules/when/lib/Scheduler.js:27:9)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
````
